language: node_js
dist: trusty
sudo: false
node_js:
- '6'
services:
- docker
install:
- docker-compose -v
script:
- docker-compose up -d
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push cbase/cbeam-telemetry-server;
  fi
env:
  global:
  - secure: ZbH41UJz5qvJqA8nr0ijY4YRT4n23s+j5YS0THUkMtH2AM8S+RIjqLm7ZTi1iGJCzPHh2Pl7NdC9qcZ/f2Cy64ZLRbWaZ46TAkzbevqrOKvDoGNa5cPvx2NYtDGbyxSSrRjo1+nTx4TVkPPYyq6AYZ4Z9GIvIUDoZIo/v4ie5I9hQhjTR6r777AHqLcjWWpAYPkPhqRPHoEldaQu2XV+A4J4/eIBAbUipkDBtBpXg+Xv05mlQz+srWv5BQizYhxlyZaaeFb5BMp2dCofXBvM0daWdS0Iaeceuid/FRe8vyp0AOUEWh/knr0svNY1SI1yauXxfeEbqz0sTrrR/PzGy0l1a5+q69l47vvsXE49n09/Rr0msakUFixnd0XLYEEDzEdrpgWk0BBL0KBrVouCv6l1+5Sxka9juEh81en059dJWaIYUqeiMGbkyYnYdYIT2L0sUMDVFw7vRaP2Z3e+g5fMrS2LhVi5ua6oMQo5qxqqbc9KbG1qfOel0oKYG6vszlTfDHPC46aO95BZdTpxkgz8l7noz74wa30rcSTRiwmEiCN5Cp5MwyJHKkJuWaEj9/eHcTI8HTWoIeiwuTty6E0V5cu0V+cHaCRPS2nZQgefBzVdGIfyyZrVLw2TEvoUmYxh5JZWAyUZus+ZpqoV5eBIWquBe95zajGHd/0C5Nc=
  - secure: dtzXmMjEtyIAqLK6LUOw1ZhKG+8j/KQVbbqe9ivpeiVcAlIlKrNivOcnObgy94NTW1pcQDb5mp5CHcCX0AqeTYn9NT5g8i1ewtnfuH4hMKaCrpb260Mst3g5+RdSzZi2oEAEbvkfZSSzxKKX9dT4Yctz8r4VsZgdF6Bsb6x+g8KrcK/BF/SLiLjpqYM5GOv5ErsaVq2+A4n6t71BkB48MUk+1DfG/+ijnaKWhpjR4JZNEIBd2TBzH58Q+G7yXcinPAtZlg57mkta/X1ZT1rpOo3KthjHSbHsGtrF+qNhRwWcK5TOYVoITvDedFgFMXW456sRq2A196k82DIj7mHVOn7EkMEMxEpdv6l76rNT8BUFaVeNktyF80rvkp+EODy8vUgN6hiWAuV55gG789aYftdHagcpL76WkuvrmfLfKXowH/+LrOOZh7bXI/UQd0zKmvL/XBt5EqjCAWmnaDcQDVmPBNm3yWFSRmrQhTdMK5PEzp5itbPsyKqXr6a8adkUMJkZSpNrFecOncjGfva4LnwZdVd8RgEWU97/+GWQ8m96rrkR0EewfoZG+n0Wou6EIPN0l7lHUE4CwcPmGKBIQ6hZMgYTq2tyjLCWn3XKz26QFXIKbCS89eoMM8NeHp0YbnvF27wyC9L4LVln8oSGmNKM4kwom7E5yUfODaOU/wM=
